update for slim 4.x
http-interop/http-factory-slim pull request #11
Opened 2022-04-28 09:06 UTC by eytienne

2022-04-28 13:58 UTC, eytienne commented on src/StreamFactory.php
> +        } catch (ValueError|Warning $error) {
I didn't get why `fopen` throws this phpunit `Warning`, some error handler to manage in a appropriate way?

2022-04-28 14:10 UTC, shadowhand requested changes

2022-04-28 14:10 UTC, shadowhand commented on composer.json
> +        "slim/slim": "^4.0",
Probably don't need `slim` itself to be required, since all the necessary classes are in `slim/psr7`.

2022-04-28 14:10 UTC, shadowhand commented on phpunit.xml.dist
> -    </logging>
Why was coverage removed?

2022-04-28 14:10 UTC, shadowhand commented on src/StreamFactory.php
> +        } catch (ValueError|Warning $error) {
Why was this changed at all? Converting another exception to a blank RuntimeException doesn't seem ideal.

2022-04-29 09:07 UTC, eytienne commented on src/StreamFactory.php
> +        } catch (ValueError|Warning $error) {
You're right, I was quite disturbed by having the tests in another repo. I will investigate the initial behaviour of the test.

2022-04-29 09:10 UTC, eytienne commented on phpunit.xml.dist
> -    </logging>
right, it just seems that the xml config schema changed with the phpunit upgrade, I will look into it for a real migration

2022-04-29 12:51 UTC, shadowhand commented on phpunit.xml.dist
> -    </logging>
```xml
  <coverage>
    <include>
      <directory suffix=".php">src/</directory>
    </include>
    <report>
      <clover outputFile="build/phpunit/clover.xml"/>
      <html outputDirectory="build/coverage" lowUpperBound="50" highLowerBound="100"/>
      <text outputFile="php://stdout" showUncoveredFiles="false" showOnlySummary="true"/>
    </report>
  </coverage>
```

2022-05-19 14:46 UTC, eytienne commented
This is no longer necessary as in slim v4 you have all these factories in `slim/psr7`.

2022-05-19 14:46 UTC, closed without merging